# Importing Numpy Library

In [1]:
import numpy as np

### Numpy Arrays

* Vectors -->> 1-D Arrays
* Matrices -->> 2-D Arrays

In [2]:
my_list = [1,2,3,4]

In [3]:
type(my_list)

list

In [5]:
my_array = np.array(my_list)
type(my_array)

numpy.ndarray

In [7]:
my_array

array([1, 2, 3, 4])

In [9]:
my_mat = [[1,2,3,11],[4,5,6,12],[7,8,9,10]]
np.array(my_mat)

array([[ 1,  2,  3, 11],
       [ 4,  5,  6, 12],
       [ 7,  8,  9, 10]])

### Built-in methods to create arrays

In [10]:
#arange : return evenly spaced values

np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [15]:
#zeros and ones

np.zeros(4)

array([0., 0., 0., 0.])

In [17]:
np.zeros((4,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [18]:
np.ones(4)

array([1., 1., 1., 1.])

In [19]:
np.ones((4,8))

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [20]:
#linspace : returns evenly spaced over a specified interval
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [21]:
np.linspace(0,5,20)

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

In [24]:
#eyes
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

## Random

* uniform distribution
* standard normal distribution
* bell curve

In [29]:
#rand : creates an array of given shape and populates it with random samples from a uniform distribution over [0,1)

np.random.rand(2)

array([0.63979281, 0.99805139])

In [35]:
np.random.rand(5,4)

array([[0.09759195, 0.51916239, 0.36591708, 0.80430837],
       [0.6851662 , 0.16427313, 0.53438055, 0.27016663],
       [0.78030558, 0.92638735, 0.41058103, 0.34292359],
       [0.669116  , 0.18869046, 0.81743404, 0.55222462],
       [0.87741047, 0.42195087, 0.21790687, 0.69662384]])

In [32]:
#randn : samples from standard normal distribution (std dev is 1)

np.random.randn(2)

array([ 0.32663588, -3.16530906])

In [36]:

np.random.randn(2,5)

array([[ 0.47073278,  0.63109083,  0.85943067,  1.37772482,  0.70526544],
       [-0.61217175, -0.34556372,  0.89309736, -0.67015221,  0.4597901 ]])

In [44]:
#randint: returns random integers from low(inclusive) to high(exclusive)

np.random.randint(1,100)

20

In [50]:
np.random.randint(1,100,30)

array([ 8,  7, 16, 43, 89, 59, 33, 49, 61, 26, 56, 19,  7, 64, 38, 94, 15,
       61, 35, 44, 62, 38, 93, 12, 35, 95, 34, 18, 64, 23])

# Seed

* sets random state, so that same random results can be reproduced

* (this is same as setting random state in machine learning train test split in sklearn and pytorch)

In [73]:
np.random.seed(10)
np.random.randint(1,500,30)

array([266, 126, 485,  16, 321, 370, 124, 157, 474, 222, 497, 414, 370,
         9,  74, 257, 491,  41, 421, 372,  17, 357, 240, 396,  55, 345,
       364, 123,  63,  34])

## Array Attributes and Method

In [87]:
arr = np.arange(20)
ranar = np.random.randint(0,50,10)

In [88]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [106]:
#shape
arr.shape

(20,)

In [92]:
#reshape: return an array containing the same datat but with a diff shape
arr_res = arr.reshape(4,5)

In [93]:
arr_res.shape

(4, 5)

In [98]:
arr_res_1_20 = arr.reshape(20,1)
arr_res_1_20

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19]])

In [99]:
arr_res_1_20.shape

(20, 1)

In [100]:
ranar

array([44, 33,  4, 29, 42,  8, 34, 11, 13, 42])

In [101]:
#max
ranar.max()

44

In [102]:
#argmax
ranar.argmax()

0

In [103]:
#min
ranar.min()

4

In [105]:
#argmin
ranar.argmin()

2

In [107]:
ranar.dtype

dtype('int64')

In [113]:
a = np.array([[1, 2], [3, 4]])

In [114]:
a

array([[1, 2],
       [3, 4]])

In [115]:
a.transpose()

array([[1, 3],
       [2, 4]])

In [116]:
ranar

array([44, 33,  4, 29, 42,  8, 34, 11, 13, 42])

In [118]:
lst = ranar.tolist()

In [119]:
type(lst)

list